# fly.toml app configuration file generated for notifico-backend on 2024-11-04T17:58:50+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'notifico-backend'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
